fix: fixed autonaming item without default company
Bloomstack/bloomstack_core pull request #483
Opened 2020-11-03 12:31 UTC by MyuddinKhatri

fixed Company error while creating item if **Default Company** not being set in **Global Defaults**

Ref: [Asana](https://app.asana.com/0/1192407896547052/1198958632787845)

2020-11-04 10:18 UTC, neilLasrado requested changes

2020-11-04 10:18 UTC, neilLasrado commented on bloomstack_core/hook_events/item.py
> +	brand_abbr = get_abbr(item.brand)
This will override the brand_abbr set on L34 & L35

2020-11-11 12:39 UTC, MyuddinKhatri commented
@neilLasrado can you please have a look?

2020-11-23 07:52 UTC, sahil28297 requested changes

2020-11-23 07:52 UTC, sahil28297 commented on bloomstack_core/hook_events/item.py
> +		brand_abbr = get_abbr(item.brand)
use else instead of `if not default company:`

2020-11-23 07:52 UTC, sahil28297 commented on bloomstack_core/hook_events/item.py
> +		item_code = "-".join(params)
move lines 38 and 39 above line 30 and combine the if statement here with the above one

2020-11-23 10:31 UTC, sahil28297 approved these changes

2020-11-23 10:32 UTC, merged