cubejs added
Bloomstack/bloomstack_core pull request #495
Opened 2020-11-16 11:54 UTC by 07061999

cubejs integration with frappe

2020-11-16 12:24 UTC, hrwX requested changes

2020-11-16 12:24 UTC, hrwX commented on bloomstack_core/bloomstack_core/page/admin_insights/admin_insights.py
> +    print("function is calling from home")
- Remove the print statements.
- Also how are you planning to put the credentials in the site config in the first place ?

2020-11-16 12:24 UTC, hrwX commented on bloomstack_core/bloomstack_core/page/admin_insights/admin_insights.js
> +				localStorage.setItem("cube_js_secret", cube_js_secret)
- do not store the credentials in localstorage

2020-11-20 11:22 UTC, hrwX requested changes

2020-11-20 11:22 UTC, hrwX commented on config.js
> +export const CUBE_JS_SECRET = "4ee295f55c613cfef9b4bb48eeeea4db7d6c9ce0fb25ebd66b7f4e6ba9409a92b85bdfbc847dec791dda588e0810246023d98e8241906f53d87dd13892eedbd4";
```suggestion
export const CUBE_JS_HOST = "https://cubejs.bloomstack.io";
export const CUBE_JS_SECRET = "XXXX";
```

2020-11-20 11:23 UTC, hrwX commented
@07061999 Why are there `min.js` files in the PR ?? They should be built and stored in sites folder.

2020-11-26 12:02 UTC, vigilantee commented
@07061999 resolve codacy issues.

2020-11-27 09:51 UTC, vigilantee approved these changes

2020-11-27 10:41 UTC, sahil28297 approved these changes

2020-11-27 10:41 UTC, merged