fix: added company letterhead to quotation authorisation
Bloomstack/bloomstack_core pull request #557
Opened 2021-02-18 15:41 UTC by hitenshKharva

Ref : [Asana](https://app.asana.com/0/1199082161983365/1199704639752076)

2021-02-22 06:27 UTC, hrwX requested changes

2021-02-22 06:27 UTC, hrwX commented on bloomstack_core/bloomstack_core/doctype/authorization_request/authorization_request.py
> +		letterhead_content = frappe.db.get_value("Letter Head", default_letterhead, "content")
check if default letter head is present

2021-02-23 05:55 UTC, nehasacher143 submitted a review, later dismissed
Looks okay

2021-02-23 11:53 UTC, hrwX requested changes

2021-02-23 11:53 UTC, hrwX commented on bloomstack_core/bloomstack_core/doctype/authorization_request/authorization_request.py
> +			letterhead_content = frappe.db.get_value("Letter Head", default_letterhead, "content")
```suggestion
		letterhead_content = ""
		if default_letterhead:
			letterhead_content = frappe.db.get_value("Letter Head", default_letterhead, "content")
```

2021-02-23 12:28 UTC, hrwX approved these changes

2021-02-23 12:28 UTC, merged