fix: add custom field in Purchase Receipt Line Item and search it in …
Bloomstack/bloomstack_core pull request #588
Opened 2021-04-29 08:51 UTC by hitenshKharva

…supplier part name in Supplier Items

Ref : [Asana Task](https://app.asana.com/0/1199082161983365/1200238400032848)

2021-04-30 09:40 UTC, hrwX requested changes

2021-04-30 09:40 UTC, hrwX commented on bloomstack_core/bloomstack_core/custom/purchase_receipt_item.json
> + ],
Remove this

2021-04-30 09:40 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +			""", {"supplier": item.get("product_name")}, as_dict=1)
- Use ORM

2021-04-30 13:00 UTC, hrwX requested changes

2021-04-30 13:00 UTC, hrwX commented on bloomstack_core/bloomstack_core/custom/purchase_receipt_item.json
> +  }
Do not add any new code

2021-04-30 13:00 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +			""", {"supplier": item.get("product_name")}, as_dict=1)
Use ORM

2021-05-03 07:38 UTC, hrwX requested changes

2021-05-03 07:38 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +			item_exists = frappe.get_all("Item", filters={"item_code": item_code}, fields=["name", "item_name"])
```suggestion
```

2021-05-03 07:38 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +				"metrc_product_name": item.get("product_name")
```suggestion
				"item_code"	: item.parent,
				"metrc_product_name": item.get("product_name")
```

2021-05-03 07:38 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +		item_code =  frappe.db.get_all(("Item Supplier", filters={"supplier_part_no": item.get("product_name")}, fields = ["parent"])
```suggestion
		item =  frappe.db.get_all(("Item Supplier", filters={"supplier_part_no": item.get("product_name")}, fields = ["parent"])
```

2021-05-05 06:55 UTC, hrwX requested changes

2021-05-05 06:55 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +			"metrc_product_name": item.get("product_name")
```suggestion
			"item_code": supplier_item and supplier_item[0].parent,
			"metrc_product_name": item.get("product_name")
```

2021-05-05 06:55 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +		item =  frappe.db.get_all(("Item Supplier", filters={"supplier_part_no": item.get("product_name")}, fields = ["parent"])
```suggestion
		supplier_item =  frappe.db.get_all(("Item Supplier", filters={"supplier_part_no": item.get("product_name")}, fields = ["parent"])
```

2021-05-05 09:06 UTC, hrwX requested changes

2021-05-05 09:06 UTC, hrwX commented on bloomstack_core/bloomtrace/transfer.py
> +			"metrc_product_name": item.get("product_name")
```suggestion
		supplier_item = frappe.db.get_all("Item Supplier", filters={"supplier_part_no": item.get("product_name")}, fields=["parent"])
		item.update({
			"item_code": supplier_item[0].parent if supplier_item else None,
			"metrc_product_name": item.get("product_name")
		})
```

2021-05-05 09:16 UTC, hrwX approved these changes

2021-05-06 05:38 UTC, sahil28297 approved these changes

2021-05-06 05:38 UTC, merged