fix: fixed error on submission of sales order to send email for delivery window time
Bloomstack/bloomstack_core pull request #595
Opened 2021-05-12 05:30 UTC by MyuddinKhatri

Ref: [Asana](https://app.asana.com/0/1192407896547052/1200233350242169)

2021-05-17 08:48 UTC, hrwX requested changes

2021-05-17 08:48 UTC, hrwX commented on bloomstack_core/hook_events/utils.py
> +		AND `tabUser`.`enabled`=1""", role) for user in users]
- Use ORM

2021-05-19 10:39 UTC, hrwX requested changes

2021-05-19 10:39 UTC, hrwX commented on bloomstack_core/hook_events/utils.py
> +	user_list = frappe.get_all("User", fields="name",
```suggestion
	user_list = frappe.get_all("User", fields=["`tabUser`.name"],
```

2021-05-19 10:39 UTC, hrwX commented on bloomstack_core/hook_events/utils.py
> +	return[user for users in user_list for user in users]
```suggestion
	return [user for users in user_list for user in users]
```

2021-05-19 10:51 UTC, hrwX requested changes

2021-05-19 10:51 UTC, hrwX commented on bloomstack_core/hook_events/utils.py
> +			["User", "name", "!=", "Administrator"],
Shouldnt it be admin and guest ?

2021-05-19 11:46 UTC, hrwX approved these changes

2021-05-19 12:12 UTC, sahil28297 approved these changes

2021-05-19 12:12 UTC, merged