fix: changed api key fieldtype to password in google settings
Bloomstack/bloomstack_core pull request #605
Opened 2021-06-04 11:46 UTC by MyuddinKhatri

2021-06-09 05:59 UTC, hrwX requested changes

2021-06-09 05:59 UTC, hrwX commented on bloomstack_core/hook_events/delivery_trip.py
> +				"key": get_decrypted_password("Google Settings", "Google Settings", "geocode_api_key"),
```suggestion
				"key": get_decrypted_password("Google Settings", "Google Settings", "api_key"),
```

2021-06-11 06:07 UTC, sahil28297 approved these changes, later dismissed

2021-06-11 06:09 UTC, sahil28297 approved these changes

2021-06-11 06:10 UTC, merged