fix: Remove the code for work order from bloomstack core
Bloomstack/bloomstack_core pull request #607
Opened 2021-06-22 20:52 UTC by shruti2323

Have removed the code from bloomstack core and moved it to erpnext.
Asana Link : - https://app.asana.com/0/1200073273462988/1200278560808264

2021-06-23 05:49 UTC, sahil28297 commented
@shruti2323 link the bloomstack_core PR over here and vice versa, both of the PRs are to be merged together.

2021-06-26 07:17 UTC, hrwX requested changes

2021-06-26 07:17 UTC, hrwX commented on bloomstack_core/patches/v0_0_1/removed_title_field_from_work_order_doc.py
> +	frappe.delete_doc_if_exists("Work Order", "title")
```suggestion
	frappe.delete_doc_if_exists("Custom Field", "Work Order-title")
```
- You have to delete the Custom Field.

2021-07-01 09:41 UTC, hrwX approved these changes

2021-07-07 06:25 UTC, sahil28297 commented
Closing this since https://github.com/Bloomstack/erpnext/pull/1396 was closed

2021-07-07 06:25 UTC, closed without merging