fix: move sales-order.py code to erpnext from bloomstack_core
Bloomstack/bloomstack_core pull request #689
Opened 2021-09-09 09:27 UTC by MyuddinKhatri

2021-09-09 11:17 UTC, vishdha requested changes
validate_batch_item call from hooks.py that should be removed in bloomstack_core hooks.py

2021-09-13 03:48 UTC, vishdha approved these changes

2021-09-14 11:32 UTC, sahil28297 requested changes
https://github.com/Bloomstack/erpnext/pull/1640#discussion_r707227770

2021-09-15 11:59 UTC, sahil28297 approved these changes

2021-09-15 12:00 UTC, merged